# Generated by Django 4.2.30 on 2026-05-19 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending Court'), ('closed', 'Closed'), ('referred', 'Referred'), ('diverted', 'Diverted')], default='open', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-opened_date'],
            },
        ),
        migrations.CreateModel(
            name='Caseworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caseworker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('violent', 'Violent')], max_length=20)),
                ('requires_court', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('rehabilitation', 'Rehabilitation'), ('diversion', 'Diversion'), ('education', 'Education'), ('counselling', 'Counselling'), ('community_service', 'Community Service')], default='rehabilitation', max_length=30)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('facilitator', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YoungPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Non-binary'), ('N', 'Prefer not to say')], max_length=1)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='NT', max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('indigenous_status', models.BooleanField(default=False)),
                ('interpreter_required', models.BooleanField(default=False)),
                ('education_status', models.CharField(choices=[('enrolled', 'Enrolled in School'), ('not_enrolled', 'Not Enrolled'), ('completed', 'Completed Year 12'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_caseworker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='cases.caseworker')),
            ],
            options={
                'verbose_name': 'Young Person',
                'verbose_name_plural': 'Young Persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('referred', 'Referred')], default='enrolled', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='cases.case')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='cases.program')),
            ],
            options={
                'ordering': ['-enrolment_date'],
            },
        ),
        migrations.CreateModel(
            name='CourtHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField()),
                ('court_name', models.CharField(max_length=200)),
                ('judge', models.CharField(blank=True, max_length=200)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('adjourned', 'Adjourned'), ('dismissed', 'Dismissed'), ('sentenced', 'Sentenced'), ('diverted', 'Diverted'), ('acquitted', 'Acquitted')], default='pending', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('next_hearing_date', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseOffence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_offence', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_offences', to='cases.case')),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_offences', to='cases.offence')),
            ],
            options={
                'verbose_name': 'Case Offence',
                'ordering': ['-date_of_offence'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='caseworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.caseworker'),
        ),
        migrations.AddField(
            model_name='case',
            name='offences',
            field=models.ManyToManyField(blank=True, related_name='cases', through='cases.CaseOffence', to='cases.offence'),
        ),
        migrations.AddField(
            model_name='case',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='cases', through='cases.Enrolment', to='cases.program'),
        ),
        migrations.AddField(
            model_name='case',
            name='young_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.youngperson'),
        ),
        migrations.AddIndex(
            model_name='youngperson',
            index=models.Index(fields=['last_name', 'first_name'], name='cases_young_last_na_0516d6_idx'),
        ),
        migrations.AddIndex(
            model_name='youngperson',
            index=models.Index(fields=['date_of_birth'], name='cases_young_date_of_6d1f21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('case', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='caseoffence',
            unique_together={('case', 'offence')},
        ),
    ]
